version: '4'
services:
  bugzdb:
    image: mysql:8.3.0
    container_name: bugzdb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  bugz:
    build: .
    container_name: bugz
    ports:
      - "8080:8080"
    depends_on:
      - bugzdb